version: '2.1'

services:
  fullstackchallenge:
    image: inidaname/ng-fullstack
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - 27017:27017