version: '2.1'

apiVersion: v1
kind: Service
metadata:
  name: inidaname/ng-fullstack
spec:
  selector:
    app: inidaname/ng-fullstack
  ports:
  - port: 3000
    targetPort: 3000

# services:
#   fullstackchallenge:
#     image: inidaname/ng-fullstack
#     environment:
#       NODE_ENV: development
#     ports:
#       - 3000:3000